### ISSUE TITLE
Recommend the Pixelgrade Assistant plugin

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/hive-lite#30]
Provide a standard notification to install our recommended plugin, [Pixelgrade Assistant](https://wordpress.org/plugins/pixelgrade-assistant/).

**Comment by vladolaru** [comment]
@georgeolaru You can have a look at the styling here https://github.com/pixelgrade/hive-lite/tree/master/inc/admin/pixelgrade-assistant-notice

**Comment by georgeolaru** [comment]
@vladolaru I improved the overall spacings and the primary button states behavior.

**Comment by georgeolaru** [comment]
@vladolaru I think this could be closed now. We pushed the update to 1.2.2 yesterday 👏
